// dom.js: Centralized DOM element management.
export function initDOM() {
    return {
        passwordModal: document.getElementById('password-modal'),
        passwordForm: document.getElementById('password-form'),
        passwordInput: document.getElementById('password-input'),
        errorMessage: document.getElementById('error-message'),
        chatContainer: document.getElementById('chat-container'),
        mainContentArea: document.getElementById('main-content-area'),
        messagesContainer: document.getElementById('messages-container'),
        chatForm: document.getElementById('chat-form'),
        chatInput: document.getElementById('chat-input'),
        sendButton: document.getElementById('send-button'),
        micButton: document.getElementById('mic-button'),
        themeSwitcher: document.getElementById('theme-switcher'),
        logoutButton: document.getElementById('logout-button'),
        clearHistoryButton: document.getElementById('clear-history-button'),
        ttsToggleButton: document.getElementById('tts-toggle'),
        uploadButton: document.getElementById('upload-button'),
        fileInput: document.getElementById('file-input'),
        attachmentsPreview: document.getElementById('attachments-preview'),
        downloadProjectButton: document.getElementById('download-project-button'),
        imageGenButton: document.getElementById('image-gen-button'),
        imageGenModal: document.getElementById('image-gen-modal'),
        imageGenForm: document.getElementById('image-gen-form'),
        imagePromptInput: document.getElementById('image-prompt-input'),
        transparentBgToggle: document.getElementById('transparent-bg-toggle'),
        cancelImageGenButton: document.getElementById('cancel-image-gen'),
        submitImageGenButton: document.getElementById('submit-image-gen'),
        imageGenLoading: document.getElementById('image-gen-loading'),
        imageGenFormContainer: document.getElementById('image-gen-form-container'),
        modalLogo: document.getElementById('modal-logo'),
        headerLogo: document.getElementById('header-logo'),
        sidebar: document.getElementById('sidebar'),
        sidebarOpenButton: document.getElementById('sidebar-open-button'),
        sidebarCloseButton: document.getElementById('sidebar-close-button'),
        combinationsList: document.getElementById('combinations-list'),
        newCombinationButton: document.getElementById('new-combination-button'),
        sidebarFooter: document.getElementById('sidebar-footer'),
    };
}